<?php

/**
 * @file
 * Contains custom_events.module.
 */

use Drupal\hello_world\Event\UserLoginEvent;

/**
 * Implements hook_user_login().
 */
function hello_world_events_user_login($account) {
  echo 'vao day';die();
  // Instantiate our event.
  $event = new UserLoginEvent($account);

  // Get the event_dispatcher service and dispatch the event.
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch(UserLoginEvent::EVENT_NAME, $event);
}
