<?php

  use Drupal\hello_world\Event\UserLoginEvent;

  function hello_world_theme($existing, $type, $theme, $path) {
    return [
      // Name of theme hook. This is used in the controller to trigger the hook
      'hello_world_theme_hook' => [
        'render element' => 'children',
        // Optionally define path to Twig template files. Defaults to ./templates
        'path' => $path . '/templates',
        'variables' => [
          'variable1' => 'Ok Now',
          'variable2' => 11,
          'variable3' => [17, 22, 'abc'],
        ],
      ],
      'hello_world_twig_block_hook' => [
        'render element' => 'children',
        'template' => 'hello-twig-block-theme-hook',
        'variables' => [
          'variable' => [5, 7, 'aaa'],
        ],
      ],
      'my_custom_field_default' => [
        'render element' => 'children',
        'template' => 'snippets-default-theme-hook',
        'variables' => [
          'source_code' => 'php',
          'source_description' => 'Snippets for PHP',
        ],
      ]
    ];
  }

  /**
   * Implements hook_user_login().
   */
  function hello_world_user_login($account) {
    // Instantiate our event.
    $event = new UserLoginEvent($account);

    // Get the event_dispatcher service and dispatch the event.
    $event_dispatcher = \Drupal::service('event_dispatcher');
    $event_dispatcher->dispatch(UserLoginEvent::EVENT_NAME, $event);
  }
